"""Adjusted fairness-aware metric computation."""

from metrics_adjuster.api import (
  adjusted_metrics,
  adjusted_metrics_report,
  compute_adjusted_metrics,
)
from metrics_adjuster.core import MetricFrames
from metrics_adjuster.reporting import (
  ReportBundle,
  build_report_bundle,
  calibrated_density_figure,
  decision_curve_comparative_model_utility_figure,
  decision_curve_figure,
  decision_curve_standard_subgroup_figure,
  decision_curve_table,
  metric_comparison_table,
  render_report_html,
  weight_ratio_figure,
  write_decision_curve_csv,
  write_decision_curve_figure,
  write_decision_curve_figures,
  write_report_figures,
)
from metrics_adjuster.types import (
  BootstrapConfig,
  CalibrationConfig,
  ColumnSpec,
  DecisionCurveConfig,
  DecisionCurvePlotConfig,
  DensityRatioConfig,
  MetricConfig,
  MetricName,
  OutputConfig,
  ReportConfig,
  ReportLabelConfig,
)

__all__ = [
  "BootstrapConfig",
  "CalibrationConfig",
  "ColumnSpec",
  "DecisionCurveConfig",
  "DecisionCurvePlotConfig",
  "DensityRatioConfig",
  "MetricConfig",
  "MetricFrames",
  "MetricName",
  "OutputConfig",
  "ReportBundle",
  "ReportConfig",
  "ReportLabelConfig",
  "adjusted_metrics",
  "adjusted_metrics_report",
  "build_report_bundle",
  "calibrated_density_figure",
  "compute_adjusted_metrics",
  "decision_curve_comparative_model_utility_figure",
  "decision_curve_figure",
  "decision_curve_standard_subgroup_figure",
  "decision_curve_table",
  "metric_comparison_table",
  "render_report_html",
  "weight_ratio_figure",
  "write_decision_curve_csv",
  "write_decision_curve_figure",
  "write_decision_curve_figures",
  "write_report_figures",
]
